---
##Aqui defino los datos globales del play, nombre, hosts, permisos, etc...
- name: Configurar servidor Rocky Linux
  hosts: servidores
  become: true


#Aqui defino las tareas que se van a realizar
  tasks:
    - name: Actualizar todos los paquetes
      dnf:
        name: '*'
        state: latest

    - name: Instalar herramientas básicas
      dnf:
        name:
          - vim
          - curl
          - wget
          - git
        state: present

    - name: Agregar repositorio oficial de Docker
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        executable: /bin/bash

    - name: Instalar Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Iniciar y habilitar Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Clonar repositorio
      ansible.builtin.git:
          repo: https://{{ lookup('env','GITHUB_TOKEN') }}@github.com/MisaelVa06/Proyecto_Flask.git
          dest: /home/mvasquez/proyectoFlask
          version: main
          force: yes

    - name: Docker Compose UP
      shell: |
        docker compose up -d
      args:
        chdir: /home/mvasquez/proyectoFlask
        executable: /bin/bash
