---
- name: Suspender contenedores
  hosts: servidores
  become: true

  tasks:

    - name: Suspender contenedores monitoreo
      ansible.builtin.shell: |
        docker compose down
        args:
        chdir: /home/ansible/monitoring
        executable: /bin/bash

    - name: Suspender contenedores flask
      ansible.builtin.shell: |
        docker compose down
        args:
        chdir: /home/mvasquez/proyectoFlask
        executable: /bin/bash
