---
- name: Actualizar todos los paquetes
  dnf:
    name: '*'
    state: latest

- name: Instalar herramientas básicas
  dnf:
    name:
      - vim
      - curl
      - wget
      - git
    state: present
