---
# tasks file for monitoring_stack
- name: Clonar repositorio
  ansible.builtin.git:
    repo: "https://{{ lookup('env','GITHUB_TOKEN') }}@github.com/MisaelVa06/DevOps---Monitoring.git"
    dest: /home/ansible/monitoring
    version: main
    force: yes

- name: Levantar contenedores con Docker Compose
  ansible.builtin.shell: |
    docker compose -f docker-compose.monitoring.yml up -d
  args:
    chdir: /home/ansible/monitoring
    executable: /bin/bash
